import type { Metadata } from "next";

import "./globals.css";
import { fontInter } from "@/config/fonts";
import { ThemeProvider } from "../providers/theme-provider";
import { ModeToggle } from "@/components/toggleLD";
import Toaster from "@/components/ui/toaster";
import { auth, signOut } from "@/auth";
import { LogOutIcon } from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fontInter.className} bg-background`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {/* <ModeToggle /> */}
          <div className="gradient-background" />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
